export const FETCH_LOGIN_TYPES = {
  REQUEST: 'FETCH_LOGIN_REQUEST',
  SUCCESS: 'FETCH_LOGIN_SUCCESS',
  ERROR: 'FETCH_LOGIN_ERROR'
};

export const FETCH_LOGOUT_TYPES = {
  REQUEST: 'FETCH_LOGOUT_REQUEST',
  SUCCESS: 'FETCH_LOGOUT_SUCCESS',
  ERROR: 'FETCH_LOGOUT_ERROR'
};

export const CLEAR_LOGIN_ERROR = 'CLEAR_LOGIN_ERROR';

export const FETCH_ARTICLE_TYPES = {
  REQUEST: 'FETCH_ARTICLE_REQUEST',
  SUCCESS: 'FETCH_ARTICLE_SUCCESS',
  ERROR: 'FETCH_ARTICLE_ERROR'
};