export const FETCH_LOGIN_TYPES = {
  REQUEST: 'FETCH_LOGIN_REQUEST',
  SUCCESS: 'FETCH_LOGIN_SUCCESS',
  ERROR: 'FETCH_LOGIN_ERROR'
};

export const FETCH_LOGOUT_TYPES = {
  REQUEST: 'FETCH_LOGOUT_REQUEST',
  SUCCESS: 'FETCH_LOGOUT_SUCCESS',
  ERROR: 'FETCH_LOGOUT_ERROR'
};

export const CLEAR_LOGIN_ERROR = 'CLEAR_LOGIN_ERROR';

export const FETCH_ARTICLE_TYPES = {
  REQUEST: 'FETCH_ARTICLE_REQUEST',
  RESULT: 'FETCH_ARTICLE_RESULT',
  ERROR: 'FETCH_ARTICLE_ERROR'
};

export const FIND_ARTICLE = 'FIND_ARTICLE'
export const ADD_ARTICLE = 'ADD_ARTICLE'
export const REMOVE_ARTICLE = 'REMOVE_ARTICLE'
export const APPROVE_ARTICLE = 'APPROVE_ARTICLE'